### ISSUE TITLE
ban!!!

### ISSUE THREAD

**Issue by y85171642** [jia110/Stimulate-the-battlefield#7]
![default](https://user-images.githubusercontent.com/5828581/41853551-9c2fdc66-78c0-11e8-91c4-1323aabb53c1.png)

**Comment by jia110** [comment]
用于开源研究  请看清楚我的文档!

**Comment by y85171642** [comment]
@jia110 是我研究过头了，我的锅，还好没有永久封禁。十年后还是一条好汉！
