### ISSUE TITLE
问下这个脚本密码怎么获取啊

### ISSUE THREAD

**Issue by xmlxin** [jia110/Stimulate-the-battlefield#8]
执行刺激战场6.25稳定变态版脚本合集.lua这个脚本  提示：密码错误，要密码加百度先生；
执行百度先生6.25更新优化密码.lua这个脚本 提示：百度先生6.25更新上天入地无所不能有问题 。

**Comment by jia110** [comment]
所有密码是我QQ

**Comment by xmlxin** [comment]
你好 版主  你qq多少啊

**Comment by xmlxin** [comment]
好的 ，感谢
